### PR TITLE
Generate RSA key pair (instead of DSA)

### PR DESCRIPTION
**Pull request by ijuma**
The same change was done in the Kafka docs: https://github.com/apache/kafka/pull/1416

Review by @alexlod.

### CODE REVIEW

**Comment by alexlod** [comment]
@ijuma does the same parameter need to be used when creating the trust store, too?

Apart from that, LGTM.

**Comment by ijuma** [comment]
We only need it when generating keys, ie `-genkey`.

**Comment by alexlod** [comment]
LGTM. Thanks @ijuma!

**Comment by ijuma** [comment]
@alexlod, I don't seem to have write access to this repository so I can't merge the PR.

**Comment by ewencp** [comment]
@ijuma Sorry about that, added this to our normal team so everyone should have write access now.

**Comment by ijuma** [comment]
Thanks Ewen!

**Comment by alexlod** [comment]
Thanks @ewencp and @ijuma!

**Pull request merged**
